---
title: "Plots for Week 4"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(xtable)

set.seed(42)
```

```{r}
MyTheme_transparent <- theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA) # get rid of key legend fill, and of the surrounding
)
```
## Histogram example

```{r}
tacos.df <- data.frame(tacos = floor(rnorm(100, 4.5, 2)))
tacos.df$tacos[tacos.df$tacos<0] <- 0
write.csv(tacos.df, "../data/wk04_tacos.csv", row.names = FALSE)

tacos.brk <- c((0:5)*2-0.5)
g <- ggplot(tacos.df, aes(x=tacos))
g <- g + geom_histogram(breaks=tacos.brk, color="black", fill="cadetblue")
g <- g + theme_bw() + MyTheme_transparent
g <- g + scale_x_continuous(breaks=(0:5)*2)
g <- g + labs(x="Number of tacos eaten per week",
              y="Frequency")

g

ggsave("../wk04_taco_hist.png", width=3.25, height=1.75, dev=png(bg = "transparent", type="Xlib"))
```

```{r, comment=""}
tacos.cut <- cut(tacos.df$tacos, breaks=tacos.brk)

xtable(table(tacos.cut))
```

## Outliers

```{r}
tacos.out.df <- rbind(tacos.df, list(tacos=13))
write.csv(tacos.out.df, "../data/wk04_tacos_out.csv", row.names = FALSE)

tacos.out.brk <- c((0:7)*2-0.5)
g <- ggplot(tacos.out.df, aes(x=tacos))
g <- g + geom_histogram(breaks=tacos.out.brk, color="black", fill="cadetblue")
g <- g + theme_bw() + scale_x_continuous(breaks=(0:7)*2)
g <- g + labs(x="Number of tacos eaten per week",
              y="Frequency")

g

ggsave("../wk04_taco_out_hist.png", width=3.25, height=1.75)
```

```{r, comment=""}
tacos.out.cut <- cut(tacos.out.df$tacos, breaks=tacos.out.brk)

xtable(table(tacos.out.cut))
```

## Normal and skewed distributions

### Normal
```{r}
tmp <- rnorm(50)
iqs.df <- data.frame(iq = floor(rnorm(1000, 100, 10)))
write.csv(iqs.df, "../data/wk04_iqs.csv", row.names = FALSE)

iqs.brk <- c((6:14)*10-0.5)
g <- ggplot(iqs.df, aes(x=iq))
g <- g + geom_histogram(breaks=iqs.brk, color="black", fill="cadetblue")
g <- g + theme_bw() + MyTheme_transparent
g <- g + scale_x_continuous(breaks=(6:14)*10)
g <- g + labs(x="IQ",
              y="Frequency")

g

ggsave("../wk04_iq_hist.png", width=3.25, height=1.75, dev=png(bg = "transparent", type="Xlib"))
```

```{r, comment=""}
iqs.cut <- cut(iqs.df$iq, breaks=iqs.brk)

xtable(table(iqs.cut))
```

### Right skew
```{r}
tmp <- rnorm(100)
iqs.right.df <- data.frame(iq = rnorm(1000, 95, 10))
iqs.right.max <- max(iqs.right.df$iq)
iqs.right.mean <- mean(iqs.right.df$iq)

iqs.right.df$iq <- floor(iqs.right.df$iq*ifelse(iqs.right.df$iq<= iqs.right.mean, 1,
                                          1 + 0.3*(iqs.right.df$iq-iqs.right.mean)/(iqs.right.max-iqs.right.mean)))

write.csv(iqs.right.df, "../data/wk04_iqs_right.csv", row.names = FALSE)

range(iqs.right.df$iq)

iqs.right.brk <- c((6:16)*10-0.5)
g <- ggplot(iqs.right.df, aes(x=iq))
g <- g + geom_histogram(breaks=iqs.right.brk, color="black", fill="cadetblue")
g <- g + theme_bw() + MyTheme_transparent
g <- g + scale_x_continuous(breaks=iqs.right.brk + 0.5)
g <- g + labs(x="IQ",
              y="Frequency")

g

ggsave("../wk04_iq_right_hist.png", width=3.25, height=1.75, dev=png(bg = "transparent", type="Xlib"))
```

```{r, comment=""}
iqs.right.cut <- cut(iqs.right.df$iq, breaks=iqs.right.brk)

xtable(table(iqs.right.cut))
```

### Left skew
```{r}
tmp <- rnorm(100)
iqs.left.df <- data.frame(iq = rnorm(1000, 95, 10))
iqs.left.min <- min(iqs.left.df$iq)
iqs.left.mean <- mean(iqs.left.df$iq)

iqs.left.df$iq <- floor(iqs.left.df$iq*ifelse(iqs.left.df$iq >= iqs.left.mean, 1,
                                          1 - 0.3*(iqs.left.mean-iqs.left.df$iq)/(iqs.left.mean-iqs.left.min)))

write.csv(iqs.left.df, "../data/wk04_iqs_left.csv", row.names = FALSE)

range(iqs.left.df$iq)

iqs.left.brk <- c((4:13)*10-0.5)
g <- ggplot(iqs.left.df, aes(x=iq))
g <- g + geom_histogram(breaks=iqs.left.brk, color="black", fill="cadetblue")
g <- g + theme_bw() + MyTheme_transparent
g <- g + scale_x_continuous(breaks=iqs.left.brk + 0.5)
g <- g + labs(x="IQ",
              y="Frequency")

g

ggsave("../wk04_iq_left_hist.png", width=3.25, height=1.75, dev=png(bg = "transparent", type="Xlib"))
```

```{r, comment=""}
iqs.left.cut <- cut(iqs.left.df$iq, breaks=iqs.left.brk)

xtable(table(iqs.left.cut))
```

## Bimodal distribution
```{r}
tacos.bi.df <- data.frame(tacos = c(round(rnorm(50, 4.5, 1.5)),
                                    round(rnorm(50, 13.5, 1.5))))
tacos.bi.df$tacos[tacos.bi.df$tacos<0] <- 0
write.csv(tacos.df, "../data/wk04_tacos_bi.csv", row.names = FALSE)
range(tacos.bi.df$tacos)

tacos.bi.brk <- c((0:9)*2-0.5)
g <- ggplot(tacos.bi.df, aes(x=tacos))
g <- g + geom_histogram(breaks=tacos.bi.brk, color="black", fill="cadetblue")
g <- g + theme_bw() + MyTheme_transparent
g <- g + scale_x_continuous(breaks=tacos.bi.brk+0.5)
g <- g + labs(x="Number of tacos eaten per week",
              y="Frequency")

g

ggsave("../wk04_taco_bi_hist.png", width=3.25, height=1.75, dev=png(bg = "transparent", type="Xlib"))
```

```{r, comment=""}
tacos.bi.cut <- cut(tacos.bi.df$tacos, breaks=tacos.bi.brk)

xtable(table(tacos.bi.cut))
```
