---
title: "Homework - Week 9"
author: "Your name here"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Questions marked with "(OS3: X.X)" are from the textbook with "X.X" as the exercise number. The answers to the odd questions (odd by book numbering that is) will be in the back of the book.

1. (OS3: 5.3) An independent random 
sample is selected from an approximately normal population with an unknown 
standard deviation. Find the p-value for the given set of hypotheses and $T$ 
test statistic. Also determine if the null hypothesis would be rejected 
at $\alpha = 0.05$.

    a. $H_A: \mu > \mu_0$, $n = 11$, $T = 1.91$

    b. $H_A: \mu < \mu_0$, $n = 17$, $T = -3.45$

    c. $H_A: \mu \ne \mu_0$, $n = 7$, $T = 0.83$

    d. $H_A: \mu > \mu_0$, $n = 28$, $T = 2.13$


2. (OS3: 5.7) New York is 
known as ``the city that never sleeps". A random sample of 25 New Yorkers 
were asked how much sleep they get per night. Statistical summaries of 
these data are shown below. Do these data provide strong evidence that New 
Yorkers sleep less than 8 hours a night on average?
\begin{center}
\begin{tabular}{rrrrrr}
 \hline
n 	& $\bar{x}$	& s		& min 	& max \\ 
 \hline
25 	& 7.73 		& 0.77 	& 6.17 	& 9.78 \\ 
  \hline
\end{tabular}
\end{center}

    a. Write the hypotheses in symbols and in words.

    b. Check conditions, then calculate the test statistic, $T$, and the 
associated degrees of freedom.

    c. Find and interpret the p-value in this context. Drawing a picture 
may be helpful.

    d. What is the conclusion of the hypothesis test?

    e. If you were to construct a 90\% confidence interval that corresponded 
to this hypothesis test, would you expect 8 hours to be in the interval?


3. (OS3: 5.19) Is there strong evidence 
of global warming? Let's consider a small scale example, comparing how temperatures 
have changed in the US from 1968 to 2008. The daily high temperature reading on 
January 1 was collected in 1968 and 2008 for 51 randomly selected locations in the 
continental US. Then the difference between the two readings (temperature in 
2008 - temperature in 1968) was calculated for each of the 51 different locations. 
The average of these 51 values was 1.1 degrees with a standard deviation of 4.9 
degrees. We are interested in determining whether these data provide strong 
evidence of temperature warming in the continental US.

    a. Is there a relationship between the observations collected in 1968 and 2008? Or are the observations in the two groups independent? Explain.

    b. Write hypotheses for this research in symbols and in words.

    c. Check the conditions required to complete this test.

    d. Calculate the test statistic and find the p-value.

    e. What do you conclude? Interpret your conclusion in context.

    f. What type of error might we have made? Explain in context what the error means.

    g. Based on the results of this hypothesis test, would you expect a confidence interval for the average difference between the temperature measurements from 1968 and 2008 to include 0? Explain your reasoning.


4. (OS3: 5.28) Prices of diamonds are determined by what is 
known as the 4 Cs: cut, clarity, color, and carat weight. The prices of diamonds go up as the 
carat weight increases, but the increase is not smooth. For example, the difference between the 
size of a 0.99 carat diamond and a 1 carat diamond is undetectable to the naked human eye, but 
the price of a 1 carat diamond tends to be much higher than the price of a 0.99 diamond. In 
this question we use two random samples of diamonds, 0.99 carats and 1 carat, each sample of 
size 23, and compare the average prices of the diamonds. In order to be able to compare 
equivalent units, we first divide the price for each diamond by 100 times its weight in carats. 
That is, for a 0.99 carat diamond, we divide the price by 99. For a 1 carat diamond, we divide 
the price by 100. The distributions and some sample statistics are shown below.

    Conduct a hypothesis test to evaluate if there is a difference between the average standardized prices of 0.99 and 1 carat diamonds. Make sure to state your hypotheses clearly, check relevant conditions, and interpret your results in context of the data.

\begin{center}
\begin{tabular}{l c c }
\hline
		& 0.99 carats	 	& 1 carat\\
\hline	
Mean 	& \$ 44.51			& \$ 56.81			 \\
SD		& \$ 13.32			&\$ 16.13			 \\
n		&23				    & 23 \\
\hline
\end{tabular}
\end{center}


5. Dataset `smoking.csv` on D2L contains the results of a clinical trial testing a drug to reduce smoking. The trial was a double-blinded randomized controlled trial with a control group which received a placebo (a fake version of the drug) and two control groups ("A" and "B"). The data represent the cigarettes per day smoked at the end of the trial for each participant.

    For each scenario below, state the null and alternative hypothesis, conduct the test, report a decision on the null hypothesis and state your conclusion in the context of the research question.

    a. The mean cigarettes per day smoked by participants before the trial started was 14.6. Use the control group to test for a placebo effect. That is, test whether the control group has a mean cigarettes per day different from 14.6.
    
    
    b. Use the control group and group A to test whether the drug was effective. That is, does group A smoke less cigarettes per day than the control group?
    
    
    c. Assume groups A and B are two separate groups of subjects. Test whether there a difference between the goups.
    
    
    d. Assume groups A and B are the same group of subjects measured at two different points in time. Test whether there is a difference in smoking over time.