---
title: "Homework - Week 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Questions marked with "(OS3: X.X)" are from the textbook with "X.X" as the exercise number. The answers to the odd questions (odd by book numbering that is) will be in the back of the book.

1. (OS3: 2.1) **True or false**. Determine if the statements below are true or false, and explain your reasoning. Determine if the statements below are true or false, and explain your reasoning. Determine if the statements below are true or false, and explain your reasoning. Determine if the statements below are true or false, and explain your reasoning. Determine if the statements below are true or false, and explain your reasoning.
    
    a. If a fair coin is tossed many times and the last eight tosses are all heads, then the chance that the next toss will be heads is somewhat less than 50\%.
    
    b. Drawing a face card (jack, queen, or king) and drawing a red card from a full deck of playing cards are mutually exclusive events.
    
    c. Drawing a face card and drawing an ace from a full deck of playing cards are mutually exclusive events.


2. (OS3: 2.5) **Coin flips.** If you flip a fair coin 10 times, what is the probability of

    a. getting all tails? 

    b. getting all heads? 

    c. getting at least one tails? 


3. (OS3: 2.6) **Dice rolls.** If you roll a pair of fair dice, what is the probability of
    
    a. getting a sum of 1?

    b. getting a sum of 5?

    c. getting a sum of 12?


4. (OS3: 2.7) **Swing voters.** A 2012 Pew Research survey asked 2,373 randomly sampled registered voters their political affiliation (Republican, Democrat, or Independent) and whether or not they identify as swing voters. 35\% of respondents identified as Independent, 23\% identified as swing voters, and 11\% identified as both.

    a. Are being Independent and being a swing voter disjoint, i.e. mutually exclusive?
    
    b. Draw a Venn diagram summarizing the variables and their associated probabilities.
    [Note: You don't have to include the diagram in your homework submission.]

    c. What percent of voters are Independent but not swing voters?
    
    d. What percent of voters are Independent or swing voters?

    e. What percent of voters are neither Independent nor swing voters?

    f. Is the event that someone is a swing voter independent of the event that someone is a political Independent?


5. (OS3: 2.8) **Poverty and language.** The American Community Survey is an ongoing survey that provides data every year to give communities the current information they need to plan investments and services. The 2010 American Community Survey estimates that 14.6\% of Americans live below the poverty line, 20.7\% speak a language other than English (foreign language) at home, and 4.2\% fall into both categories.

    a. Are living below the poverty line and speaking a foreign language at home disjoint?

    b. Draw a Venn diagram summarizing the variables and their associated probabilities.
    [Note: You don't have to include the diagram in your homework submission.]

    c. What percent of Americans live below the poverty line and only speak English at home?

    d. What percent of Americans live below the poverty line or speak a foreign language at home?

    e. What percent of Americans live above the poverty line and only speak English at home? 

    f. Is the event that someone lives below the poverty line independent of the event that the person speaks a foreign language at home?


6. (OS3: 2.9) **Disjoint vs. independent.** In parts~(a) and~(b), identify whether the events are disjoint, independent, or neither (events cannot be both disjoint and independent).

    a. You and a randomly selected student from your class both earn A's in this course. 
    
    b. You and your class study partner both earn A's in this course.

    c. If two events can occur at the same time, must they be dependent?


7. (OS3: 2.10) **Guessing on an exam.** In a multiple choice exam, there are 5 questions and 4 choices for each question (a, b, c, d). Nancy has not studied for the exam at all and decides to randomly guess the answers. What is the probability that:

    a. the first question she gets right is the $5^{th}$ question?

    b. she gets all of the questions right?

    c. she gets at least one question right?


8. (OS3: 2.14) **Health coverage, frequencies.** The 
Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey 
designed to identify risk factors in the adult population and report emerging 
health trends. The following table summarizes two variables for the respondents: 
health status and health coverage, which describes whether each respondent had 
health insurance.
\begin{center}
\begin{tabular}{rrrrrrrr}
                    &       & \multicolumn{5}{c}{\textit{Health Status}} &  \\ 
\cline{3-7}
                    &       & Excellent & Very good & Good  & Fair  & Poor  & Total\\ 
\cline{2-8}
\textit{Health}     & No    & 459       & 727       & 854   & 385   & 99    & 2,524 \\ 
\textit{Coverage}   & Yes   & 4,198     & 6,245     & 4,821 & 1,634 & 578   & 17,476 \\ 
\cline{2-8}
                    & Total & 4,657     & 6,972     & 5,675 & 2,019 & 677   & 20,000
\end{tabular}
\end{center}

    a. If we draw one individual at random, what is the probability that the 
respondent has excellent health and doesn't have health coverage?

    b. If we draw one individual at random, what is the probability that the 
respondent has excellent health or doesn't have health coverage?
